### ISSUE TITLE
Confusing incomplete pattern warnings when using pattern synonyms

### ISSUE THREAD

**Issue by ratherforky** [int-e/haskell-src-exts-simple#9]
By default, the pattern match checker "assumes that any match involving a pattern synonym will fail. As a result, any pattern match on a pattern synonym is regarded as incomplete unless the user adds a catch-all case." ([User guide](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/pragmas.html#complete-pragmas))

This unfortunately negates some of the simplicity of the library and produces unhelpful/confusing incomplete pattern warnings. For example:

```haskell
getNameString :: Name -> String
getNameString (Ident str) = str
getNameString (Symbol str) = str
```

Produces the warning:

```haskell
src/Example.hs:68:1: warning: [GHC-62161] [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘getNameString’:
        Patterns of type ‘Name’ not matched:
            Language.Haskell.Exts.Syntax.Ident _ _
            Language.Haskell.Exts.Syntax.Symbol _ _
   |
68 | getNameString (Ident str) = str
   |
```

It doesn't recognise that every case is actually covered and it shows the underlying constructors with their extra parameters.

Thankfully, this problem can be fixed using `COMPLETE` pragmas, which I'm making a PR for.

**Comment by int-e** [comment]
I published a 1.23.1.0 release with your contribution. Thanks once more!
